---
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  test:
    parameters:
      ruby-version:
        type: "string"
    docker:
      - image: 'cimg/ruby:<< parameters.ruby-version >>-browsers'
        environment:
          PGHOST: 127.0.0.1
          PGUSER: mudd
          RAILS_ENV: test
      - image: postgres:13
        environment:
          POSTGRES_USER: mudd
          POSTGRES_DB: mudd_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - ruby/install-deps

      # ensure we have psql which we need for db:schema:load
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt-get install -y postgresql-client || true

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database template
          command: |
            cp config/database.yml.tpl config/database.yml
      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:migrate
      # Run rspec
      - run:
          name: Run rspec
          command: |
            bundle exec rspec
      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - persist_to_workspace:
          root: '~/project'
          paths: '*'
workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["3.1.3"]
